---
title: "Tablas ANP"
format: html
---
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<style>
body {
    font-family: 'Montserrat';font-size: 22px;
}
</style>


<br>
<br>

<h2 style="color: #8B2323;"> Áreas Naturales Protegidas federales según su categoría de manejo</h2>

```{r echo=FALSE, include=FALSE}
library(dplyr)
library(RPostgres)
library(knitr)
library(kableExtra)
library(DT) #interactive table
library(scales)

library(readr)

```


```{r echo=FALSE, include=FALSE}
# con <- dbConnect(
#   RPostgres::Postgres(),
#   dbname = "sub_monitoreo",   
#   host = "localhost",                     
#   port = 5432,  
#   user = "postgres", 
#   password = "monitoreo2024"
# )
# 
# tables = dbListTables(con)


# df_anp <- dbGetQuery(con, "SELECT * FROM anp")
# df_region <- dbGetQuery(con, "SELECT * FROM region")
# df_catmanejo <- dbGetQuery(con, "SELECT * FROM cat_manejo")
```


```{r echo=FALSE, include=FALSE}

 library(RMySQL)  # O RMariaDB
# 
# con <- dbConnect(
#   RMySQL::MySQL(),
#   dbname = "monitoreo",
#   host = "localhost",  
#   username = "root",
#   password = ""
# )
# 
# tables = dbListTables(con)
# df_anp <- dbGetQuery(con, "SELECT * FROM anp")
# df_region <- dbGetQuery(con, "SELECT * FROM region")
# df_anpporregiones <- dbGetQuery(con, "SELECT * FROM regionales")
# df_catmanejo <- dbGetQuery(con, "SELECT * FROM cat_manejo")
# df_vegetation <- dbGetQuery(con, "SELECT * FROM vegetation")
# entidades_anp <- dbGetQuery(con, "SELECT * FROM surfaceanp_entity")
# names(df_anp)
# names(df_region)
# names(df_catmanejo)

#write_excel_csv(df_anp,"datos_anp30sept24.xlsx")
```
 
 
```{r echo=FALSE, message=FALSE, warning=FALSE}
con <- dbConnect(
  RMySQL::MySQL(),
  dbname = "numeralia",
  host = "localhost",  
  username = "root",
  password = ""
)

tables = dbListTables(con)
df_anp <- dbGetQuery(con, "SELECT * FROM anp")
df_region <- dbGetQuery(con, "SELECT * FROM region")
df_anpporregiones <- dbGetQuery(con, "SELECT * FROM regionales")
df_catmanejo <- dbGetQuery(con, "SELECT * FROM cat_manejo")
df_vegetation <- dbGetQuery(con, "SELECT * FROM vegetation")
entidades_anp <- dbGetQuery(con, "SELECT * FROM surfaceanp_entity")

```


```{r echo=FALSE}
summary_catmanejo <- df_anp %>%
  left_join(df_catmanejo, by = "id_catmanejo") %>%  
  group_by(abrev_cat) %>%   
  summarise(
    num_anp = n(),   
    superficie_total = round(sum(sup_total, na.rm = TRUE))   
  ) %>%
  mutate(
    total_superficie = sum(superficie_total),  
    Porcentaje = round((superficie_total / total_superficie) * 100,2)  
  ) %>%
  select(abrev_cat, num_anp, superficie_total, Porcentaje)

tot = data.frame(
  abrev_cat = "Total", 
  num_anp = sum(summary_catmanejo$num_anp),
  superficie_total = round(sum(df_anp$sup_total)),
  Porcentaje = round(sum(summary_catmanejo$Porcentaje))
)



summary_catmanejo <- rbind(summary_catmanejo, tot)

summary_catmanejo$superficie_total <- scales::comma(summary_catmanejo$superficie_total)


colnames(summary_catmanejo) <- c("Categoría", "Número de ANP", "Superficie total (ha)", "Porcentaje del total protegido (%)")


datatable(summary_catmanejo, 
          options = list(pageLength = 8, autoWidth = TRUE, 
                         dom = 't',  # Solo mostrar la tabla sin paginación
                         class = 'cell-border text-center')) %>%
  formatStyle(columns = colnames(summary_catmanejo), 
              `text-align` = 'center')

```

<h2 style="color: #8B2323;">Superficie protegida del territorio nacional en las ANP federales</h2>


```{r echo=FALSE}
resumen_superficies <- df_anp %>%
#  group_by(id_superficie) %>%  # Agrupar por id_superficie
  summarise(
    num_anp = n(),  # Contar cuántas ANP tienen ese tipo de superficie
    superficie_t_total = sum(sup_terrestre, na.rm = TRUE),
    superficie_m_total = sum(sup_marina, na.rm = TRUE)
  )

superficies <- data.frame(
  tipo_superficie = c("Terrestre", "Marina"),
  num_anp = c(192, 40),
  superficie =c(scales::comma(resumen_superficies$superficie_t_total),
                scales::comma(resumen_superficies$superficie_m_total)
                ),
  Porcentaje_total = c(23.57, 76.43),
  porc_territorio =c("11.76 de la superficie terrestre nacional", 
                     "11.76 de la superficie terrestre nacional"
                     )
)

colnames(superficies) <- c(
  "Tipo de superficie",
  "Número de ANP",
  "Superficie (ha)",
  "Porcentaje del total protegido ANP %",
  "Porcentaje del territorio nacional"
)

kable(superficies, format = "html", table.attr = "class='table table-striped'") %>%
  kable_styling(full_width = F, position = "center")


```

<h2 style="color: #8B2323;"> Protección de tipos de vegetación y uso de suelo en las ANP Federales </h2>


```{r echo=FALSE}
vegetacion <- dbGetQuery(con, "SELECT * FROM vegetation")
colnames(vegetacion) <- c("ID","Tipo de vegetación o ecosistema",
                          "Superficie dentro de las ANP (ha)",
                          "Porcentaje del total protegido por ANP federales (%)"
                          )

#kable(vegetacion[-1], format = "html", table.attr = "class='table table-striped'") %>%
#  kable_styling(full_width = F, position = "center")



datatable(vegetacion[-1], 
          options = list(pageLength = 20, autoWidth = TRUE, 
                         dom = 't',  # Solo mostrar la tabla sin paginación
                         class = 'cell-border text-center')) %>%
  formatStyle(columns = colnames(vegetacion[-1]), 
              `text-align` = 'center')
```

<h2 style="color: #8B2323;"> Distribución de superficies de las ANP federales por entidad federativa </h2>


```{r echo=FALSE}

entidades_anp <- read_csv("C:/Users/israel.monjaraz/OneDrive - Food and Agriculture Organization/Documentos/ProjectCodes/r/numeralia_anp/data/anp_entidad_federativa_08102024.csv",show_col_types = FALSE)

entidades_anp <- dbGetQuery(con, "SELECT * FROM surfaceanp_entity")


entidades_anp = as.data.frame(entidades_anp)
entidades_anp$surface_entity = scales::comma(entidades_anp$surface_entity)
entidades_anp = entidades_anp[-c(1,3)]
colnames(entidades_anp) =c(
  "Entidad Federativa",
  "Superficie dentro de la entidad (ha)"
)

datatable(entidades_anp, 
          options = list(
              pageLength = 10,  # Mostrar 10 filas por página
              autoWidth = TRUE, 
              dom = 'ftipr',    # Mostrar la tabla con paginación y barra de búsqueda
              class = 'cell-border text-center'
          )) %>%
  formatStyle(
      columns = colnames(entidades_anp), 
      `text-align` = 'center'
  )

```





 
 